[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
    "-C", "force-frame-pointers",
    "-C", "link-arg=-Trom_functions.x",
]

[build]
#target = "riscv32imac-esp-espidf.json"
target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = [ "core", "alloc" ]
#build-std = [ "core" ]
